import { useEffect, useState } from "react";
import { DateOptions } from "@/tabs/HR/JobManagement/ListJobs";
import { FaComment, FaEdit, FaHeart } from "react-icons/fa";
import { notify } from "./Notification";
import { useMutation } from "@tanstack/react-query";
import api from "@/api/api";
import { useAuth } from "@/context/AuthContext";
import { Button } from "../ui/button";
import { MdDelete } from "react-icons/md";
import { useNavigate } from "react-router-dom";

export interface Author {
  email: string;
  name: string;
  userId: number;
  profileUrl: string;
  designation: string;
}

export interface Comment {
  id: number;
  message: string;
  user: Author;
}

export interface PostResponse {
  author: Author | null;
  commentCount: number;
  createdAt: string;
  deleted: boolean;
  description: string;
  imagePath: string;
  likeCount: number;
  postId: number;
  postType: string;
  tags: string;
  title: string;
  visibleToEmp: boolean;
  visibleToManager: boolean;
  likes?: Author[];
  likedByMe: boolean;
  comments?: Comment[];
}

const DEFAULT_PROFILE =
  "https://betterwaterquality.com/wp-content/uploads/2020/09/dummy-profile-pic-300x300-1-1.png";

export default function PostBox({
  post,
  onOpenLikes,
  onOpenComments,
  onCommentCountChange,
  onDelete,
  onWarnRequest,
  mypost,
}: {
  post: PostResponse;
  onOpenLikes: (id: number) => void;
  onOpenComments: (id: number) => void;
  onCommentCountChange?: (delta: number) => void;
  onDelete?: (postId: number) => void;
  onWarnRequest?: (postId: number) => void;
  mypost: boolean;
}) {
  const { user } = useAuth();
  const navigate = useNavigate();

  const [likeCounts, setLikeCounts] = useState(post.likeCount);
  const [commentCounts, setCommentCounts] = useState(post.commentCount);
  const [isLiked, setLiked] = useState<boolean>(post.likedByMe);

  useEffect(() => {
    setLikeCounts(post.likeCount);
  }, [post.likeCount]);

  useEffect(() => {
    setCommentCounts(post.commentCount);
  }, [post.commentCount]);

  const addLike = useMutation({
    mutationFn: async () => {
      return await api.patch(
        `/post/like/post/${post.postId}/user/${user?.userId}`,
      );
    },
    onError: (error: any) => {
      notify.error("Error", error.response?.data?.message);
      setLiked(false);
      setLikeCounts((prev) => prev - 1);
    },
  });

  const removeLike = useMutation({
    mutationFn: async () => {
      return await api.delete(
        `/post/like/post/${post.postId}/user/${user?.userId}`,
      );
    },
    onError: (error: any) => {
      notify.error("Error", error.response?.data?.message);
      setLiked(true);
      setLikeCounts((prev) => prev + 1);
    },
  });

  const deletePost = useMutation({
    mutationFn: async () => {
      return await api.delete(`/post`, {
        data: { postId: post.postId, deletedById: user?.userId },
      });
    },
    onSuccess: () => {
      notify.success("Success", "Post deleted successfully");
      onDelete?.(post.postId);
    },
    onError: (error: any) => {
      notify.error("Error", error.response?.data?.message);
      console.error(error.response);
    },
  });

  const deletePostWithWarning = useMutation({
    mutationFn: async () => {
      return await api.delete(`/post`, {
        data: { postId: post.postId, deletedById: user?.userId },
      });
    },
    onSuccess: () => {
      notify.success("Success", "Post deleted successfully");
      onDelete?.(post.postId);
    },
    onError: (error: any) => {
      notify.error("Error", error.response?.data?.message);
      console.error(error.response);
    },
  });

  const handleLike = async () => {
    if (!user) return;

    const newLiked = !isLiked;
    setLiked(newLiked);
    setLikeCounts((prev) => (newLiked ? prev + 1 : prev - 1));

    try {
      if (newLiked) {
        await addLike.mutateAsync();
      } else {
        await removeLike.mutateAsync();
      }
    } catch {}
  };

  const isSystem = post.author === null;

  const profile =
    !isSystem &&
    post.author?.profileUrl &&
    post.author.profileUrl.trim().length > 0
      ? post.author.profileUrl
      : DEFAULT_PROFILE;

  return (
    <div className="w-full flex justify-center">
      <div className="gap-4 p-5 md:max-w-200 md:min-w-120 m-5 rounded-2xl bg-white shadow-md w-full">
        <div className="flex items-center gap-3">
          <img
            src={profile}
            alt="profile"
            className="w-15 h-15 rounded-full object-cover"
          />

          <div>
            <p className="font-bold text-lg">
              {isSystem ? "Generated by the system" : post.author?.name}
            </p>

            <p className="text-sm text-gray-500">
              {isSystem ? "System Notification" : post.author?.designation}
              {" • "}
              {new Date(post.createdAt).toLocaleDateString(
                undefined,
                DateOptions,
              )}
            </p>
          </div>
          {mypost && (
            <div className="ml-auto">
              <Button
                type="button"
                className="text-red hover:bg-red-500 hover:text-white"
                onClick={async () => await deletePost.mutateAsync()}
              >
                <MdDelete />
              </Button>
              <Button
                type="button"
                className="text-black hover:bg-gray-500 hover:text-white"
                onClick={() => navigate(`../update/${post.postId}`)}
              >
                <FaEdit />
              </Button>
            </div>
          )}
          {user?.role === "HR" && !mypost && (
            <div className="ml-auto">
              <Button
                type="button"
                className="text-yellow-600 hover:bg-yellow-500 hover:text-white"
                onClick={() => onWarnRequest?.(post.postId)}
              >
                Warn & Delete
              </Button>
            </div>
          )}
        </div>
        <div className="relative cursor-pointer" onDoubleClick={handleLike}>
          <div className="text-xl font-bold mt-4">{post.title}</div>

          {post.postType === "I" && (
            <div className="relative my-4 w-full max-h-125 flex items-center justify-center overflow-hidden rounded-xl">

              <img
                src={post.imagePath}
                alt="blur-bg"
                className="absolute inset-0 w-full h-full object-cover blur-xl scale-110 opacity-80"
              />

              <img
                src={post.imagePath}
                alt="post"
                className="relative max-h-125 w-auto object-contain"
              />
            </div>
          )}

          <div>{post.description}</div>
          <div>{post.tags}</div>
        </div>

        <hr className="my-4 text-gray-300" />
        <div className="flex gap-6">
          <div className="flex items-center gap-2 cursor-pointer hover:text-red-500 transition">
            <FaHeart
              className={isLiked ? "text-red-500" : ""}
              onClick={handleLike}
            />
            <p
              onClick={() => onOpenLikes(post.postId)}
              className={isLiked ? "text-red-500" : ""}
            >
              {likeCounts}
            </p>
          </div>

          <div
            className="flex items-center gap-2 cursor-pointer hover:text-blue-500 transition"
            onClick={() => onOpenComments(post.postId)}
          >
            <FaComment />
            {commentCounts}
          </div>
        </div>
      </div>
    </div>
  );
}
